namespace sThuoc.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class _26 : DbMigration
    {
        public override void Up()
        {
            DropForeignKey("dbo.LoaiXuatNhaps", "MaNhaThuoc", "dbo.NhaThuocs");
            DropForeignKey("dbo.PhieuKiemKeChiTiets", "MaNhaThuoc", "dbo.NhaThuocs");
            DropForeignKey("dbo.BacSies", "MaNhaThuoc", "dbo.NhaThuocs");
            DropForeignKey("dbo.PhieuKiemKes", "MaNguoiTao", "dbo.UserProfile");
            DropForeignKey("dbo.DangBaoChes", "MaNhaThuoc", "dbo.NhaThuocs");
            DropForeignKey("dbo.DonViTinhs", "MaNhaThuoc", "dbo.NhaThuocs");
            DropForeignKey("dbo.NhomKhachHangs", "NhaThuoc_MaNhaThuoc", "dbo.NhaThuocs");
            DropForeignKey("dbo.NhomNhaCungCaps", "MaNhaThuoc", "dbo.NhaThuocs");
            DropForeignKey("dbo.NhomThuocs", "MaNhaThuoc", "dbo.NhaThuocs");
            DropForeignKey("dbo.Nuocs", "MaNhaThuoc", "dbo.NhaThuocs");
            DropForeignKey("dbo.PhieuKiemKes", "MaNhaThuoc", "dbo.NhaThuocs");
            DropForeignKey("dbo.PhieuThuChis", "NhaThuoc_MaNhaThuoc", "dbo.NhaThuocs");
            DropForeignKey("dbo.PhieuXuats", "NhaThuoc_MaNhaThuoc", "dbo.NhaThuocs");
            DropForeignKey("dbo.Thuocs", "NhomThuoc_MaNhomThuoc", "dbo.NhomThuocs");
            DropForeignKey("dbo.PhieuNhapChiTiets", "PhieuNhap_MaPhieuNhap", "dbo.PhieuNhaps");
            DropForeignKey("dbo.PhieuKiemKeChiTiets", "MaPhieuKiemKe", "dbo.PhieuKiemKes");
            DropForeignKey("dbo.UserPermissions", "NhaThuoc_MaNhaThuoc", "dbo.NhaThuocs");
            DropIndex("dbo.BacSies", new[] { "MaNhaThuoc" });
            DropIndex("dbo.DangBaoChes", new[] { "MaNhaThuoc" });
            DropIndex("dbo.Thuocs", new[] { "NhomThuoc_MaNhomThuoc" });
            DropIndex("dbo.DonViTinhs", new[] { "MaNhaThuoc" });
            DropIndex("dbo.PhieuNhapChiTiets", new[] { "PhieuNhap_MaPhieuNhap" });
            DropIndex("dbo.NhomKhachHangs", new[] { "NhaThuoc_MaNhaThuoc" });
            DropIndex("dbo.PhieuThuChis", new[] { "NhaThuoc_MaNhaThuoc" });
            DropIndex("dbo.NhomNhaCungCaps", new[] { "MaNhaThuoc" });
            DropIndex("dbo.PhieuXuats", new[] { "NhaThuoc_MaNhaThuoc" });
            DropIndex("dbo.LoaiXuatNhaps", new[] { "MaNhaThuoc" });
            DropIndex("dbo.NhomThuocs", new[] { "MaNhaThuoc" });
            DropIndex("dbo.Nuocs", new[] { "MaNhaThuoc" });
            DropIndex("dbo.PhieuKiemKeChiTiets", new[] { "ThuocId" });
            DropIndex("dbo.PhieuKiemKeChiTiets", new[] { "MaNhaThuoc" });
            DropIndex("dbo.PhieuKiemKes", new[] { "MaNguoiTao" });
            DropIndex("dbo.UserPermissions", new[] { "NhaThuoc_MaNhaThuoc" });
            RenameColumn(table: "dbo.PhieuKiemKeChiTiets", name: "ThuocId", newName: "Thuoc_ThuocId");
            AddColumn("dbo.PhieuKiemKes", "NguoiTao_UserId", c => c.Int());
            AddColumn("dbo.NhaThuocs", "HoatDong", c => c.Boolean(nullable: false));
            AlterColumn("dbo.BacSies", "MaNhaThuoc", c => c.String(nullable: false, maxLength: 128));
            AlterColumn("dbo.DangBaoChes", "MaNhaThuoc", c => c.String(nullable: false, maxLength: 128));
            AlterColumn("dbo.Thuocs", "NhomThuoc_MaNhomThuoc", c => c.Int(nullable: false));
            AlterColumn("dbo.DonViTinhs", "MaNhaThuoc", c => c.String(nullable: false, maxLength: 128));
            AlterColumn("dbo.PhieuNhapChiTiets", "PhieuNhap_MaPhieuNhap", c => c.Int(nullable: false));
            AlterColumn("dbo.NhomKhachHangs", "NhaThuoc_MaNhaThuoc", c => c.String(nullable: false, maxLength: 128));
            AlterColumn("dbo.PhieuThuChis", "NhaThuoc_MaNhaThuoc", c => c.String(nullable: false, maxLength: 128));
            AlterColumn("dbo.NhomNhaCungCaps", "MaNhaThuoc", c => c.String(nullable: false, maxLength: 128));
            AlterColumn("dbo.PhieuXuats", "NhaThuoc_MaNhaThuoc", c => c.String(nullable: false, maxLength: 128));
            AlterColumn("dbo.NhomThuocs", "MaNhaThuoc", c => c.String(nullable: false, maxLength: 128));
            AlterColumn("dbo.Nuocs", "MaNhaThuoc", c => c.String(nullable: false, maxLength: 128));
            AlterColumn("dbo.PhieuKiemKeChiTiets", "Thuoc_ThuocId", c => c.Int());
            AlterColumn("dbo.UserPermissions", "NhaThuoc_MaNhaThuoc", c => c.String(nullable: false, maxLength: 128));
            CreateIndex("dbo.BacSies", "MaNhaThuoc");
            CreateIndex("dbo.DangBaoChes", "MaNhaThuoc");
            CreateIndex("dbo.Thuocs", "NhomThuoc_MaNhomThuoc");
            CreateIndex("dbo.DonViTinhs", "MaNhaThuoc");
            CreateIndex("dbo.PhieuNhapChiTiets", "PhieuNhap_MaPhieuNhap");
            CreateIndex("dbo.NhomKhachHangs", "NhaThuoc_MaNhaThuoc");
            CreateIndex("dbo.PhieuThuChis", "NhaThuoc_MaNhaThuoc");
            CreateIndex("dbo.NhomNhaCungCaps", "MaNhaThuoc");
            CreateIndex("dbo.PhieuXuats", "NhaThuoc_MaNhaThuoc");
            CreateIndex("dbo.NhomThuocs", "MaNhaThuoc");
            CreateIndex("dbo.Nuocs", "MaNhaThuoc");
            CreateIndex("dbo.PhieuKiemKeChiTiets", "Thuoc_ThuocId");
            CreateIndex("dbo.PhieuKiemKes", "NguoiTao_UserId");
            CreateIndex("dbo.UserPermissions", "NhaThuoc_MaNhaThuoc");
            AddForeignKey("dbo.BacSies", "MaNhaThuoc", "dbo.NhaThuocs", "MaNhaThuoc", cascadeDelete: true);
            AddForeignKey("dbo.PhieuKiemKes", "NguoiTao_UserId", "dbo.UserProfile", "UserId");
            AddForeignKey("dbo.DangBaoChes", "MaNhaThuoc", "dbo.NhaThuocs", "MaNhaThuoc", cascadeDelete: true);
            AddForeignKey("dbo.DonViTinhs", "MaNhaThuoc", "dbo.NhaThuocs", "MaNhaThuoc", cascadeDelete: true);
            AddForeignKey("dbo.NhomKhachHangs", "NhaThuoc_MaNhaThuoc", "dbo.NhaThuocs", "MaNhaThuoc", cascadeDelete: true);
            AddForeignKey("dbo.NhomNhaCungCaps", "MaNhaThuoc", "dbo.NhaThuocs", "MaNhaThuoc", cascadeDelete: true);
            AddForeignKey("dbo.NhomThuocs", "MaNhaThuoc", "dbo.NhaThuocs", "MaNhaThuoc", cascadeDelete: true);
            AddForeignKey("dbo.Nuocs", "MaNhaThuoc", "dbo.NhaThuocs", "MaNhaThuoc", cascadeDelete: true);
            AddForeignKey("dbo.PhieuKiemKes", "MaNhaThuoc", "dbo.NhaThuocs", "MaNhaThuoc", cascadeDelete: true);
            AddForeignKey("dbo.PhieuThuChis", "NhaThuoc_MaNhaThuoc", "dbo.NhaThuocs", "MaNhaThuoc", cascadeDelete: true);
            AddForeignKey("dbo.PhieuXuats", "NhaThuoc_MaNhaThuoc", "dbo.NhaThuocs", "MaNhaThuoc", cascadeDelete: true);
            AddForeignKey("dbo.Thuocs", "NhomThuoc_MaNhomThuoc", "dbo.NhomThuocs", "MaNhomThuoc", cascadeDelete: true);
            AddForeignKey("dbo.PhieuNhapChiTiets", "PhieuNhap_MaPhieuNhap", "dbo.PhieuNhaps", "MaPhieuNhap", cascadeDelete: true);
            AddForeignKey("dbo.PhieuKiemKeChiTiets", "MaPhieuKiemKe", "dbo.PhieuKiemKes", "MaPhieuKiemKe", cascadeDelete: true);
            AddForeignKey("dbo.UserPermissions", "NhaThuoc_MaNhaThuoc", "dbo.NhaThuocs", "MaNhaThuoc", cascadeDelete: true);
            DropColumn("dbo.LoaiXuatNhaps", "MaNhaThuoc");
            DropColumn("dbo.PhieuKiemKeChiTiets", "MaNhaThuoc");
        }
        
        public override void Down()
        {
            AddColumn("dbo.PhieuKiemKeChiTiets", "MaNhaThuoc", c => c.String(nullable: false, maxLength: 128));
            AddColumn("dbo.LoaiXuatNhaps", "MaNhaThuoc", c => c.String(maxLength: 128));
            DropForeignKey("dbo.UserPermissions", "NhaThuoc_MaNhaThuoc", "dbo.NhaThuocs");
            DropForeignKey("dbo.PhieuKiemKeChiTiets", "MaPhieuKiemKe", "dbo.PhieuKiemKes");
            DropForeignKey("dbo.PhieuNhapChiTiets", "PhieuNhap_MaPhieuNhap", "dbo.PhieuNhaps");
            DropForeignKey("dbo.Thuocs", "NhomThuoc_MaNhomThuoc", "dbo.NhomThuocs");
            DropForeignKey("dbo.PhieuXuats", "NhaThuoc_MaNhaThuoc", "dbo.NhaThuocs");
            DropForeignKey("dbo.PhieuThuChis", "NhaThuoc_MaNhaThuoc", "dbo.NhaThuocs");
            DropForeignKey("dbo.PhieuKiemKes", "MaNhaThuoc", "dbo.NhaThuocs");
            DropForeignKey("dbo.Nuocs", "MaNhaThuoc", "dbo.NhaThuocs");
            DropForeignKey("dbo.NhomThuocs", "MaNhaThuoc", "dbo.NhaThuocs");
            DropForeignKey("dbo.NhomNhaCungCaps", "MaNhaThuoc", "dbo.NhaThuocs");
            DropForeignKey("dbo.NhomKhachHangs", "NhaThuoc_MaNhaThuoc", "dbo.NhaThuocs");
            DropForeignKey("dbo.DonViTinhs", "MaNhaThuoc", "dbo.NhaThuocs");
            DropForeignKey("dbo.DangBaoChes", "MaNhaThuoc", "dbo.NhaThuocs");
            DropForeignKey("dbo.PhieuKiemKes", "NguoiTao_UserId", "dbo.UserProfile");
            DropForeignKey("dbo.BacSies", "MaNhaThuoc", "dbo.NhaThuocs");
            DropIndex("dbo.UserPermissions", new[] { "NhaThuoc_MaNhaThuoc" });
            DropIndex("dbo.PhieuKiemKes", new[] { "NguoiTao_UserId" });
            DropIndex("dbo.PhieuKiemKeChiTiets", new[] { "Thuoc_ThuocId" });
            DropIndex("dbo.Nuocs", new[] { "MaNhaThuoc" });
            DropIndex("dbo.NhomThuocs", new[] { "MaNhaThuoc" });
            DropIndex("dbo.PhieuXuats", new[] { "NhaThuoc_MaNhaThuoc" });
            DropIndex("dbo.NhomNhaCungCaps", new[] { "MaNhaThuoc" });
            DropIndex("dbo.PhieuThuChis", new[] { "NhaThuoc_MaNhaThuoc" });
            DropIndex("dbo.NhomKhachHangs", new[] { "NhaThuoc_MaNhaThuoc" });
            DropIndex("dbo.PhieuNhapChiTiets", new[] { "PhieuNhap_MaPhieuNhap" });
            DropIndex("dbo.DonViTinhs", new[] { "MaNhaThuoc" });
            DropIndex("dbo.Thuocs", new[] { "NhomThuoc_MaNhomThuoc" });
            DropIndex("dbo.DangBaoChes", new[] { "MaNhaThuoc" });
            DropIndex("dbo.BacSies", new[] { "MaNhaThuoc" });
            AlterColumn("dbo.UserPermissions", "NhaThuoc_MaNhaThuoc", c => c.String(maxLength: 128));
            AlterColumn("dbo.PhieuKiemKeChiTiets", "Thuoc_ThuocId", c => c.Int(nullable: false));
            AlterColumn("dbo.Nuocs", "MaNhaThuoc", c => c.String(maxLength: 128));
            AlterColumn("dbo.NhomThuocs", "MaNhaThuoc", c => c.String(maxLength: 128));
            AlterColumn("dbo.PhieuXuats", "NhaThuoc_MaNhaThuoc", c => c.String(maxLength: 128));
            AlterColumn("dbo.NhomNhaCungCaps", "MaNhaThuoc", c => c.String(maxLength: 128));
            AlterColumn("dbo.PhieuThuChis", "NhaThuoc_MaNhaThuoc", c => c.String(maxLength: 128));
            AlterColumn("dbo.NhomKhachHangs", "NhaThuoc_MaNhaThuoc", c => c.String(maxLength: 128));
            AlterColumn("dbo.PhieuNhapChiTiets", "PhieuNhap_MaPhieuNhap", c => c.Int());
            AlterColumn("dbo.DonViTinhs", "MaNhaThuoc", c => c.String(maxLength: 128));
            AlterColumn("dbo.Thuocs", "NhomThuoc_MaNhomThuoc", c => c.Int());
            AlterColumn("dbo.DangBaoChes", "MaNhaThuoc", c => c.String(maxLength: 128));
            AlterColumn("dbo.BacSies", "MaNhaThuoc", c => c.String(maxLength: 128));
            DropColumn("dbo.PhieuKiemKes", "NguoiTao_UserId");
            DropColumn("dbo.NhaThuocs", "HoatDong");
            RenameColumn(table: "dbo.PhieuKiemKeChiTiets", name: "Thuoc_ThuocId", newName: "ThuocId");
            CreateIndex("dbo.UserPermissions", "NhaThuoc_MaNhaThuoc");
            CreateIndex("dbo.PhieuKiemKes", "MaNguoiTao");
            CreateIndex("dbo.PhieuKiemKeChiTiets", "MaNhaThuoc");
            CreateIndex("dbo.PhieuKiemKeChiTiets", "ThuocId");
            CreateIndex("dbo.Nuocs", "MaNhaThuoc");
            CreateIndex("dbo.NhomThuocs", "MaNhaThuoc");
            CreateIndex("dbo.LoaiXuatNhaps", "MaNhaThuoc");
            CreateIndex("dbo.PhieuXuats", "NhaThuoc_MaNhaThuoc");
            CreateIndex("dbo.NhomNhaCungCaps", "MaNhaThuoc");
            CreateIndex("dbo.PhieuThuChis", "NhaThuoc_MaNhaThuoc");
            CreateIndex("dbo.NhomKhachHangs", "NhaThuoc_MaNhaThuoc");
            CreateIndex("dbo.PhieuNhapChiTiets", "PhieuNhap_MaPhieuNhap");
            CreateIndex("dbo.DonViTinhs", "MaNhaThuoc");
            CreateIndex("dbo.Thuocs", "NhomThuoc_MaNhomThuoc");
            CreateIndex("dbo.DangBaoChes", "MaNhaThuoc");
            CreateIndex("dbo.BacSies", "MaNhaThuoc");
            AddForeignKey("dbo.UserPermissions", "NhaThuoc_MaNhaThuoc", "dbo.NhaThuocs", "MaNhaThuoc");
            AddForeignKey("dbo.PhieuKiemKeChiTiets", "MaPhieuKiemKe", "dbo.PhieuKiemKes", "MaPhieuKiemKe");
            AddForeignKey("dbo.PhieuNhapChiTiets", "PhieuNhap_MaPhieuNhap", "dbo.PhieuNhaps", "MaPhieuNhap");
            AddForeignKey("dbo.Thuocs", "NhomThuoc_MaNhomThuoc", "dbo.NhomThuocs", "MaNhomThuoc");
            AddForeignKey("dbo.PhieuXuats", "NhaThuoc_MaNhaThuoc", "dbo.NhaThuocs", "MaNhaThuoc");
            AddForeignKey("dbo.PhieuThuChis", "NhaThuoc_MaNhaThuoc", "dbo.NhaThuocs", "MaNhaThuoc");
            AddForeignKey("dbo.PhieuKiemKes", "MaNhaThuoc", "dbo.NhaThuocs", "MaNhaThuoc");
            AddForeignKey("dbo.Nuocs", "MaNhaThuoc", "dbo.NhaThuocs", "MaNhaThuoc");
            AddForeignKey("dbo.NhomThuocs", "MaNhaThuoc", "dbo.NhaThuocs", "MaNhaThuoc");
            AddForeignKey("dbo.NhomNhaCungCaps", "MaNhaThuoc", "dbo.NhaThuocs", "MaNhaThuoc");
            AddForeignKey("dbo.NhomKhachHangs", "NhaThuoc_MaNhaThuoc", "dbo.NhaThuocs", "MaNhaThuoc");
            AddForeignKey("dbo.DonViTinhs", "MaNhaThuoc", "dbo.NhaThuocs", "MaNhaThuoc");
            AddForeignKey("dbo.DangBaoChes", "MaNhaThuoc", "dbo.NhaThuocs", "MaNhaThuoc");
            AddForeignKey("dbo.PhieuKiemKes", "MaNguoiTao", "dbo.UserProfile", "UserId");
            AddForeignKey("dbo.BacSies", "MaNhaThuoc", "dbo.NhaThuocs", "MaNhaThuoc");
            AddForeignKey("dbo.PhieuKiemKeChiTiets", "MaNhaThuoc", "dbo.NhaThuocs", "MaNhaThuoc");
            AddForeignKey("dbo.LoaiXuatNhaps", "MaNhaThuoc", "dbo.NhaThuocs", "MaNhaThuoc");
        }
    }
}
