// <auto-generated />
namespace sThuoc.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class _49 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_49));
        
        string IMigrationMetadata.Id
        {
            get { return "201604090459498_49"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
